# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = 'a650c044004c2f983a6642f773f0400d'
  config.secret_key = '0360df82dab060518d5644ad8075398f'
  config.default_from = 'dreamrock@hotmail.fr'
  # Mailjet API v3.1 is at the moment limited to Send API.
  # We’ve not set the version to it directly since there is no other endpoint in that version.
  # We recommend you create a dedicated instance of the wrapper set with it to send your emails.
  # If you're only using the gem to send emails, then you can safely set it to this version.
  # Otherwise, you can remove the dedicated line into config/initializers/mailjet.rb.
  config.api_version = 'v3.1'
end
